// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmgkozhlxmyppqvihlpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtZ2tvemhseG15cHBxdmlobHBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDQ2MTksImV4cCI6MjA2NDY4MDYxOX0.y5quRGc1VtWf-GWbQAFl7IwOZAFX7Vc8Yjv3ibYg0k8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);